version: "3"

services:
  api-database:
    image: mongo:3.2.4
    container_name: api-database
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: paw-demo
    container_name: paw-demo
    ports:
      - 8080:8080
    links:
      - api-database
    depends_on:
      - api-database
